data:
  dataset_card: lbox/lbox_open
  training_set_name: train
  validation_set_name: validation
  test_set_name: test2
  use_local_data: false
  path_train:
  path_valid:
  path_test:

model:
  decoder_max_length: 1024
  input_template_type: 0
  model_type: generative
  max_seq_length: 1021
  task: ljp_civil
  subtask: civil
  target_field: facts
  target_parses_dict:
    claim_acceptance_lv:
      - claim_acceptance_lv
  path_template:
  plm:
    freeze: false
    eval_mode: false
    name: legal-gpt
    path: lbox/lcube-base
    revision:
  precision: bf16

train:
  accelerator: auto
  accumulate_grad_batches: 2
  limit_val_batches: 1.0
  batch_size: 4
  batch_size_prediction: 12
  check_val_every_n_epoch: 1
  fast_dev_run: false
  max_epochs: 15
  multiple_trainloader_mode:
  seed: 1
  strategy: null
  weight:
    trained: false
    path: data/models/casename.lv1.d0.1.1.e1.lgpt_tune_plm_only.yaml/epoch=3-step=5335.ckpt
    save_path_dir: ./data/models
    do_not_load_pretrained_weight: false
    old_format: false
  log_dir: ./logs
  optim:
    gradient_clip_val: 1.0
    gradient_clip_algorithm: norm
    prompt:
      lr: 0.1
      optimizer_type: adamw
      lr_scheduler_type: warmup_constant
      lr_scheduler_param:
        warmup_constant:
          num_warmup_steps: 10
    plm:
      lr: 0.00005
      optimizer_type: adamw
    swa:
      use: true
      lr: 0.00005
      swa_epoch_start: 4
      annealing_epochs: 6
  profiler: null
  num_sanity_val_steps: 0
  val_check_interval: 0.5
  validation_metric: em
  validation_target_parse: claim_acceptance_lv
  validation_sub_param:
    method: text_em
    target_sub_parse:

infer:
  max_length:
  max_new_tokens: 3
  min_length: 1
  temperature: 1.0
  do_sample: False
  top_k: 0
  top_p: 0.9
  repetition_penalty: 1.0
  num_beams: 1
  bad_words_ids: null
  parse_sep_token: "*"
  value_sep_token: "|"
  empty_token: "없음"

  